### ISSUE TITLE
No cpu temperature data in zabbix.

### ISSUE THREAD

**Issue by lixxdee** [dmytro-tsepilov/zabbix_sensors#1]
I have a server with two cpu. I get data in temperature.txt, but this data does not go to zabbix. What can be wrong? :)

![5464564](https://user-images.githubusercontent.com/48026553/151011427-0d562bdc-acee-4641-a47d-40077a8781d5.png)

![23453445](https://user-images.githubusercontent.com/48026553/151011430-0eccd494-3909-4043-acad-813d1d380e9b.png)

**Comment by dmytro-tsepilov** [comment]
Hi,

can you show discovery.txt file?
I suppose the issue could be there. I didn't test it with n-cpu instances.

**Comment by lixxdee** [comment]
Wow! Didn't expect such a quick response! :)
`[{"{#DEVICE_NAME}":"sda","{#DEVICE_MODEL}":"KINGSTONSUV500120G","{#DEVICE_TYPE}":"storage"},{"{#DEVICE_NAME}":"sdb","{#DEVICE_MODEL}":"KINGSTONSUV400S37480G","{#DEVICE_TYPE}":"storage"},{"{#DEVICE_NAME}":"sdc","{#DEVICE_MODEL}":"WDCWD10EZEX-08WN4A0","{#DEVICE_TYPE}":"storage"},{"{#DEVICE_NAME}":"sdd","{#DEVICE_MODEL}":"ST1000DM003-1CH162","{#DEVICE_TYPE}":"storage"},{"{#DEVICE_NAME}":"sde","{#DEVICE_MODEL}":"WDCWD1002FAEX-00Z3A0","{#DEVICE_TYPE}":"storage"},{"{#DEVICE_NAME}":"sdf","{#DEVICE_MODEL}":"TOSHIBAHDWD110","{#DEVICE_TYPE}":"storage"},{"{#DEVICE_NAME}":"core0","{#DEVICE_MODEL}":"Core_0","{#DEVICE_TYPE}":"cpu"},{"{#DEVICE_NAME}":"core0","{#DEVICE_MODEL}":"Core_0","{#DEVICE_TYPE}":"cpu"}]`

**Comment by dmytro-tsepilov** [comment]
Yep, that's the one of the issues. As you can see in discovery file both CPU have same #DEVICE_NAME - core0, that could be the reason, why agent can't read the value.

**Comment by lixxdee** [comment]
> Yep, that's the one of the issues. As you can see in discovery file both CPU have same #DEVICE_NAME - core0, that could be the reason, why agent can't read the value.

Is there a way to fix this in your code? :)

**Comment by dmytro-tsepilov** [comment]
Yes, I think it possible.
Can you please run 'sensors' command on your server, and show me full output here?

**Comment by lixxdee** [comment]
> Yes, I think it possible. Can you please run 'sensors' command on your server, and show me full output here?

Good!)

w83793-i2c-0-2f
Adapter: SMBus I801 adapter at 1100
VcoreA:        1.12 V  (min =  +0.92 V, max =  +1.49 V)
VcoreB:        1.12 V  (min =  +0.92 V, max =  +1.49 V)
in2:           1.09 V  (min =  +1.08 V, max =  +1.33 V)
in3:         512.00 mV (min =  +0.38 V, max =  +0.69 V)
in4:           1.52 V  (min =  +1.34 V, max =  +1.65 V)
in5:           3.31 V  (min =  +2.96 V, max =  +3.63 V)
in6:         984.00 mV (min =  +0.90 V, max =  +1.10 V)
+5V:           5.14 V  (min =  +4.52 V, max =  +5.50 V)
5VSB:          5.07 V  (min =  +4.52 V, max =  +5.50 V)
Vbat:          3.18 V  (min =  +2.70 V, max =  +3.30 V)
fan1:        4703 RPM  (min =  712 RPM)
fan2:        4856 RPM  (min =  712 RPM)
fan3:        4856 RPM  (min =  712 RPM)
fan4:           0 RPM  (min =  712 RPM)  ALARM
fan5:        4981 RPM  (min =  712 RPM)
fan6:        4671 RPM  (min =  712 RPM)
fan7:           0 RPM  (min =  712 RPM)  ALARM
fan8:           0 RPM  (min =  712 RPM)  ALARM
fan9:           0 RPM  (min =  712 RPM)  ALARM
fan10:          0 RPM  (min =  712 RPM)  ALARM
temp1:        +25.0°C  (high = +70.0°C, hyst = +65.0°C)  sensor = Intel PECI
temp2:        +24.0°C  (high = +70.0°C, hyst = +65.0°C)  sensor = Intel PECI
temp3:       -128.0°C  (high = +70.0°C, hyst = +65.0°C)  sensor = Intel PECI
temp4:       -128.0°C  (high = +70.0°C, hyst = +65.0°C)  sensor = Intel PECI
temp5:        +24.0°C  (high = +50.0°C, hyst = +45.0°C)  sensor = thermistor
intrusion0:  OK
beep_enable: disabled

i5k_amb-isa-0000
Adapter: ISA adapter
Ch. 0 DIMM 0:  +36.0°C  (low  = +93.0°C, high = +124.0°C)
Ch. 0 DIMM 1:  +45.5°C  (low  = +91.5°C, high = +124.0°C)
Ch. 0 DIMM 2:  +48.5°C  (low  = +104.5°C, high = +124.0°C)
Ch. 0 DIMM 3:  +38.5°C  (low  = +103.5°C, high = +124.0°C)
Ch. 1 DIMM 0:  +38.0°C  (low  = +93.0°C, high = +124.0°C)
Ch. 1 DIMM 1:  +42.0°C  (low  = +91.5°C, high = +124.0°C)
Ch. 1 DIMM 2:  +38.0°C  (low  = +104.5°C, high = +124.0°C)
Ch. 1 DIMM 3:  +35.5°C  (low  = +103.5°C, high = +124.0°C)
Ch. 2 DIMM 0:  +32.5°C  (low  = +93.0°C, high = +124.0°C)
Ch. 2 DIMM 1:  +30.5°C  (low  = +91.5°C, high = +124.0°C)
Ch. 2 DIMM 2:  +38.0°C  (low  = +104.5°C, high = +124.0°C)
Ch. 2 DIMM 3:  +36.0°C  (low  = +103.5°C, high = +124.0°C)
Ch. 3 DIMM 0:  +38.0°C  (low  = +93.0°C, high = +124.0°C)
Ch. 3 DIMM 1:  +36.5°C  (low  = +91.5°C, high = +124.0°C)
Ch. 3 DIMM 2:  +43.0°C  (low  = +104.5°C, high = +124.0°C)
Ch. 3 DIMM 3:  +31.5°C  (low  = +103.5°C, high = +124.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +38.0°C  (high = +82.0°C, crit = +100.0°C)
Core 1:       +38.0°C  (high = +82.0°C, crit = +100.0°C)
Core 2:       +44.0°C  (high = +82.0°C, crit = +100.0°C)
Core 3:       +44.0°C  (high = +82.0°C, crit = +100.0°C)

w83627hf-isa-0290
Adapter: ISA adapter
in0:           3.81 V  (min =  +0.00 V, max =  +4.08 V)
in1:           3.89 V  (min =  +0.00 V, max =  +4.08 V)
in2:           3.84 V  (min =  +2.82 V, max =  +3.79 V)  ALARM
in3:           3.07 V  (min =  +0.24 V, max =  +1.76 V)  ALARM
in4:           3.06 V  (min =  +0.88 V, max =  +3.57 V)
in5:           3.02 V  (min =  +1.52 V, max =  +0.86 V)  ALARM
in6:           3.07 V  (min =  +3.76 V, max =  +0.10 V)  ALARM
in7:           3.34 V  (min =  +4.05 V, max =  +1.25 V)  ALARM
in8:           3.23 V  (min =  +0.91 V, max =  +1.78 V)  ALARM
fan1:           0 RPM  (min = 3629 RPM, div = 2)  ALARM
fan2:           0 RPM  (min =    0 RPM, div = 2)
fan3:           0 RPM  (min = 8544 RPM, div = 2)  ALARM
temp1:        -48.0°C  (high = +79.0°C, hyst = +47.0°C)  sensor = thermistor
temp2:        -48.0°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor
temp3:        -48.0°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor
cpu0_vid:    +1.419 V
beep_enable: enabled

coretemp-isa-0001
Adapter: ISA adapter
Core 0:       +41.0°C  (high = +82.0°C, crit = +100.0°C)
Core 1:       +39.0°C  (high = +82.0°C, crit = +100.0°C)
Core 2:       +41.0°C  (high = +82.0°C, crit = +100.0°C)
Core 3:       +42.0°C  (high = +82.0°C, crit = +100.0°C)

**Comment by dmytro-tsepilov** [comment]
Thanks, I will work on fix

**Comment by dmytro-tsepilov** [comment]
@lixxdee I updated script to support multi-cpu instances. Please check.
To update just checkout latest commit. No configuration changes required if you use auto-discover template by zabbix.
In case manual configuration of sensor Items you need to update keys.

**Comment by lixxdee** [comment]
> @lixxdee I updated script to support multi-cpu instances. Please check. To update just checkout latest commit. No configuration changes required if you use auto-discover template by zabbix. In case manual configuration of sensor Items you need to update keys.

Good job, man! This works well for me! Thank you! :)
![ew5435t4](https://user-images.githubusercontent.com/48026553/151061804-2f885e93-96c6-4c61-b4f0-b3c5b9d4e441.png)
![g4545g](https://user-images.githubusercontent.com/48026553/151061826-5f4dc7e0-3cf6-42e4-bc22-305d9fe4cef2.png)
