### ISSUE TITLE
Add grep $ anchor to lsblk

### ISSUE THREAD

**Issue by lixxdee** [dmytro-tsepilov/zabbix_sensors#2]
To ensure that the script works, we suggest adding the grep $ anchor in the temperature.sh script on line number 6
`disks=$(lsblk -o NAME,TYPE | grep -E 'disk$'| awk '{printf " "$1}')`

**Comment by dmytro-tsepilov** [comment]
Done, added

**Comment by lixxdee** [comment]
Good! :)

**Comment by lixxdee** [comment]
This was the right thing to do for me because cron was talking about an error in the script and was reading lvm zero disks in PROXMOX. I hope you understand what I'm talking about)
![dbfed466-40e7-4875-867b-2e9c8d51944c](https://user-images.githubusercontent.com/48026553/151950754-ae800501-05da-4931-a0c1-c7b99c82deff.jpg)
![80414955-0f6a-4006-84b0-ccd66b49e755](https://user-images.githubusercontent.com/48026553/151950772-ee4fb160-b2fb-474c-a4ff-c1a5d641e421.jpg)

**Comment by dmytro-tsepilov** [comment]
@lixxdee Yep, sure) I guessed that lsblk return some useless data in your case, and $ help to cut that)
Thanks for suggestions ;-)
